#!/usr/bin/env node
var spawn = require('child_process').spawn;

var spawnArgs = [];
var startAdding = false;
process.argv.forEach(function(val, index, array){
  if(startAdding){
    spawnArgs.push(val);
  } else {
    if(val.indexOf('hack-mainframe') > -1) startAdding = true;
  }
});

spawn('ssh', spawnArgs, {
  stdio: [
  0,
  1,
  2
  ]
});
